services:
  proxy:
    build: .
    ports:
      - 8080:8080
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10
    restart: always
    user: postgres
    environment:
      POSTGRES_PASSWORD: postgres
  adminer:
    image: adminer
    restart: always
    ports:
      - "8282:8282"
    command:
        - 'php'
        - '-S'
        - '[::]:8282'
        - '-t'
        - '/var/www/html'