CREATE SCHEMA IF NOT EXISTS proxy;
CREATE TABLE IF NOT EXISTS proxy.requests
(
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scheme TEXT,
    host TEXT,
    path TEXT,
    URI  TEXT,
    body TEXT,
    raw  TEXT
);

CREATE TABLE IF NOT EXISTS proxy.parameters
(
    id     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id INT references proxy.requests (id),
    encoding TEXT,
    method TEXT,
    key   TEXT,
    value   TEXT
);

CREATE TABLE IF NOT EXISTS proxy.request_headers
(
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id INT references proxy.requests (id),
    key        TEXT,
    value      TEXT
);

CREATE TABLE IF NOT EXISTS proxy.responses
(
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id INT references proxy.requests (id),
    status INT,
    body text
);

CREATE TABLE IF NOT EXISTS proxy.response_headers
(
    id         INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    response_id INT references proxy.responses (id),
    key        TEXT,
    value      TEXT
);

